"""user table location column default value nullable false

Revision ID: 6370b9718340
Revises: 054e5a9079c2
Create Date: 2025-03-25 14:39:06.354520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6370b9718340'
down_revision: Union[str, None] = '054e5a9079c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
