"""creating article table

Revision ID: 8de19cb25736
Revises: 60736dfcd912
Create Date: 2025-04-01 23:06:37.893506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8de19cb25736'
down_revision: Union[str, None] = '60736dfcd912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('article', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('article', sa.Column('published_at', sa.DateTime(), nullable=False))
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    op.drop_column('article', 'createdAt')
    op.drop_column('article', 'publishedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('publishedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'author_id')
    op.drop_column('article', 'published_at')
    op.drop_column('article', 'created_at')
    op.drop_column('article', 'is_published')
    # ### end Alembic commands ###
