"""user table removed age column

Revision ID: 93f53ee3e506
Revises: d604a1ef2353
Create Date: 2025-03-25 14:55:05.516989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f53ee3e506'
down_revision: Union[str, None] = 'd604a1ef2353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), server_default=sa.text('18'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
