"""user table removed age column

Revision ID: bc8d3022f900
Revises: c50d767a4f58
Create Date: 2025-03-25 14:53:13.153724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8d3022f900'
down_revision: Union[str, None] = 'c50d767a4f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.VARCHAR(), server_default=sa.text('18'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
